n =  new Date();
y = n.getFullYear();
m = n.getMonth() + 1;
d = n.getDate();
patata=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"]
pipo=["Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado"]
m=patata[m-1]
s=n.getDay()
s=pipo[s]
document.getElementById("date").innerHTML =s+" "+ d + " de " + m + " del " + y;